# Generated by Django 2.1.7 on 2019-06-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_annotation_batch_content_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='num_completed',
            field=models.IntegerField(default=0),
        ),
    ]
