# Generated by Django 2.1.7 on 2019-06-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_batch_num_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
